/**
 * Markdown Writer Module
 * Writes rendered content to .md files with metadata headers
 */

import * as path from 'path';
import * as fs from 'fs';
import { logger } from '../utils/logger';

/**
 * Metadata for the generated document
 */
export interface DocMetadata {
  generatedAt: string;
  classification: string;
  sourceArtifacts: number;
  confidenceSummary: {
    high: number;
    medium: number;
    low: number;
  };
}

/**
 * Write rendered content to a markdown file with metadata header
 * @param renderedContent - The rendered markdown content
 * @param docType - Type of document (e.g., 'adr', 'runbook')
 * @param projectPath - Root path of the project
 * @param metadata - Document metadata
 * @returns Full path to the written file
 */
export function writeMarkdown(
  renderedContent: string,
  docType: string,
  projectPath: string,
  metadata: DocMetadata
): string {
  // Create docs/generated directory
  const docsDir = path.join(projectPath, 'docs', 'generated');
  if (!fs.existsSync(docsDir)) {
    fs.mkdirSync(docsDir, { recursive: true });
    logger.debug('Created docs/generated directory', { path: docsDir });
  }

  // Generate metadata header comment
  const metadataHeader = generateMetadataHeader(metadata, docType);

  // Combine metadata header with content
  const fullContent = metadataHeader + '\n\n' + renderedContent;

  // Write to file
  const outputPath = path.join(docsDir, `${docType}.md`);
  fs.writeFileSync(outputPath, fullContent, 'utf-8');

  logger.info('Markdown written', {
    docType,
    path: outputPath,
    size: fullContent.length,
  });

  return outputPath;
}

/**
 * Generate the metadata header comment for a document
 */
function generateMetadataHeader(metadata: DocMetadata, docType: string): string {
  const lines = [
    '<!-- Generated by Vibe Doc v0.1.0 -->',
    `<!-- Date: ${metadata.generatedAt} -->`,
    `<!-- Classification: ${metadata.classification} -->`,
    `<!-- Source artifacts: ${metadata.sourceArtifacts} files scanned -->`,
    `<!-- Confidence: ${metadata.confidenceSummary.high} high, ${metadata.confidenceSummary.medium} medium, ${metadata.confidenceSummary.low} low sections -->`,
  ];

  return lines.join('\n');
}
